### ISSUE TITLE
Compliments bunched up in one issue✨

### ISSUE THREAD

**Issue by rooberrydev** [fac24/week1-asmahan-george-bereket-maria#17]
Well done! You've made great progress for two days of work🕺
Modularised server routes, a random colour selector for the blog posts, delete functionality - lots of v cool things going on

![](https://media.giphy.com/media/SVH9y2LQUVVCRcqD7o/giphy.gif)

**Comment by rooberrydev** [comment]
Also

https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/5f0d54275871ee94a9231f6a78510d7a0dfa05de/public/style.css#L1-L9

loving the use of css variables for custom colour classes!!🙌

https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/5f0d54275871ee94a9231f6a78510d7a0dfa05de/public/style.css#L109-L131

**Comment by joe-dev-public** [comment]
Collected compliments from all of team 3 :)

- Modular code
- Can delete messages
  - Elegant/concise code
  - Good use of postKey to select which post to delete!
- Nice design 🎨 
- Good readme! (Thanks for the local install instructions)
- Heroku deployment works :)

**Comment by mariaalouisaa** [comment]
Thank you!! 💃🕺
