### ISSUE TITLE
Leave more comments as you go along 👀

### ISSUE THREAD

**Issue by rooberrydev** [fac24/week1-asmahan-george-bereket-maria#19]
https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/5f0d54275871ee94a9231f6a78510d7a0dfa05de/routes/home.js#L19-L24

especially for bits of code like this colour index resetting when you hit the end of the colours array - the code makes sense but its always good to add comments explaining what you've done.

Makes it easier for other team members and yourself to look back and understand the code at a glance!

**Comment by oliverjam** [comment]
Yeah it's generally a good idea to leave a comment explaining _why_ you did something (the code serves as the _what_). E.g. here I can see from the code that you are resetting the index back to zero, but I don't have the context to know why you need to do that.
