### ISSUE TITLE
Make use of co-commits! 

### ISSUE THREAD

**Issue by rooberrydev** [fac24/week1-asmahan-george-bereket-maria#20]
There's quite a difference in commits in your contributions graph - likely because you were pairing and working from one person's laptop. For the next project, do make use of [co-authored commits](https://github.com/fac24/cohort/blob/main/co-authoring-emails.md) so everyone gets credit 🕺🏾 

![](https://media.giphy.com/media/3o6UBbsOZ3co6fJHLG/giphy-downsized-large.gif)

**Comment by mariaalouisaa** [comment]
Good tip!!!
