### ISSUE TITLE
Some notes on npm/dependencies (.gitignore!)

### ISSUE THREAD

**Issue by rooberrydev** [fac24/week1-asmahan-george-bereket-maria#22]
1) Your `node_modules` folder has ended up on GitHub - this isn't ideal - it makes your project size a lot larger than it needs to be when pushing and pulling to GitHub!

- A good way to think about this is that the `package.json` file is a list of instructions that tell your computer what to install (from the npm servers, not GitHub) to run your project. So everyone shares the `package.json` over GitHub. 

- But there's no need to share the actual downloaded modules over GitHub- since you'll most likely only need to install them once per project, and the `package-lock.json` file will make sure that team members don't get different versions of the dependencies.

- During your project setup be sure to create a `.gitignore` file (before pushing!) so git knows not to include your `node_modules` folder.

2) I noticed in your readme the instructions mention installing all the packages one by one. This is unnecessary - your package.json already has the list of modules needed for your project, so when somebody new clones it, all they need to run to install the modules is `npm install` or the shortform `npm i`. This reads from the package.json and installs everything listed under "dependencies" or "devDependencies". 

When you are adding a new dependency to your project- that's when you do`npm install "dependency-name"`

**Comment by rooberrydev** [comment]
woops joe and oli left the same issue about npm install.

**Comment by mariaalouisaa** [comment]
Thanks for the tips!!
