### ISSUE TITLE
Consider using ``npm install`` in readme instructions

### ISSUE THREAD

**Issue by joe-dev-public** [fac24/week1-asmahan-george-bereket-maria#23]
Instead of three separate commands (below), you could instruct other devs to do ``npm install`` 🙂 

As long as your ``package.json`` is set up correctly, I think this should install all the required dependencies in one go?

https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/a7cde397f0c7344f8a15c0ecf65e27ed58d1c082/README.md?plain=1#L28-L29

https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/a7cde397f0c7344f8a15c0ecf65e27ed58d1c082/README.md?plain=1#L34

**Comment by oliverjam** [comment]
Yeah telling people to manually install things that are already listed in your `package.json` dependencies could cause issues, as it will prompt npm to update the dependency and change the `package-lock.json`.

See also my issue here: https://github.com/fac24/week1-alex-hallie-hussain-sonia/issues/32

**Comment by mariaalouisaa** [comment]
Thanks for the tips!!!
