### ISSUE TITLE
Avoid duplicating labels

### ISSUE THREAD

**Issue by oliverjam** [fac24/week1-asmahan-george-bereket-maria#24]
https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/a7cde397f0c7344f8a15c0ecf65e27ed58d1c082/routes/home.js#L11

Here you've set both a visible text label (the text content of the button) _and_ an `aria-label`. These are different, which might be confusing to a sighted user using assistive tech (some people do this). Generally if you have a visible label you don't need to override with an `aria-label`, unless the visible one would be confusing (e.g. if it's just `x` or something).

**Comment by oliverjam** [comment]
(Also while I'm here, I don't think the `required` attribute works on buttons 😅)

**Comment by AsmahanM** [comment]
Thanks, @oliverjam!
