### ISSUE TITLE
object keys our strings 

### ISSUE THREAD

**Issue by PJSalter** [fac24/week1-asmahan-george-bereket-maria#25]
very neat code,  🤩  there is just one little minor detail, its smart to use numbers 🔢  as the object keys, although just as a friendly tip, these aren't actually numbers and instead strings 🧵 . Our team had a little problem with this when we came across it. 👀 

A huge congrats on the deployment, this was amazing to see ✨ 

https://github.com/fac24/week1-asmahan-george-bereket-maria/blob/a7cde397f0c7344f8a15c0ecf65e27ed58d1c082/blogPosts.js#L2

**Comment by mariaalouisaa** [comment]
Thanks for the tip!
